# Generated by Django 5.2.13 on 2026-05-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_tenant__41a1c8_idx',
            old_name='audit_audit_tenant__abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_actor_i_58da28_idx',
            old_name='audit_audit_actor_created_idx',
        ),
    ]
