# Generated by Django 6.0.2 on 2026-02-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField()),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hik_gateways",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=128)),
                ("dev_index", models.CharField(max_length=64, unique=True)),
                (
                    "device_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "protocol_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                (
                    "offline_hint",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hik_devices",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="hik_gateway.gateway",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dev_index", models.CharField(max_length=64)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(max_length=64)),
                ("event_datetime", models.DateTimeField()),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                ("payload", models.JSONField()),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_events",
                        to="hik_gateway.device",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hik_raw_events",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_id", models.CharField(blank=True, default="", max_length=128)),
                ("timestamp", models.DateTimeField()),
                ("attendance_type", models.CharField(max_length=64)),
                (
                    "source",
                    models.CharField(
                        choices=[("realtime", "Realtime"), ("catchup", "Catchup")],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hik_attendance_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_logs",
                        to="hik_gateway.device",
                    ),
                ),
                (
                    "raw_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_log",
                        to="hik_gateway.rawevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_event_time", models.DateTimeField(blank=True, null=True)),
                (
                    "last_search_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("last_result_position", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursor",
                        to="hik_gateway.device",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["last_event_time"],
                        name="hik_gateway_last_ev_a1d9e5_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="gateway",
            index=models.Index(
                fields=["tenant"], name="hik_gateway_tenant__d41abc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["tenant", "serial_number"],
                name="hik_gateway_tenant__5d6733_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["dev_index"], name="hik_gateway_dev_ind_67d5ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status"], name="hik_gateway_status_cc1977_idx"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("tenant", "serial_number"), name="uq_hik_device_tenant_sn"
            ),
        ),
        migrations.AddIndex(
            model_name="rawevent",
            index=models.Index(
                fields=["tenant", "dev_index", "event_datetime"],
                name="hik_gateway_tenant__0535c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawevent",
            index=models.Index(
                fields=["event_type"], name="hik_gateway_event_t_113c29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancelog",
            index=models.Index(
                fields=["tenant", "timestamp"], name="hik_gateway_tenant__4660ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancelog",
            index=models.Index(
                fields=["person_id"], name="hik_gateway_person__6913d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancelog",
            index=models.Index(
                fields=["attendance_type"], name="hik_gateway_attenda_701dd7_idx"
            ),
        ),
    ]
