# Generated by Django 6.0.2 on 2026-02-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hik_gateway', '0002_access_event_erd_alignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicereaderconfig',
            new_name='idx_hik_access_dev_door_reader',
            old_name='idx_hik_rawevent_dev_door_reader',
        ),
    ]
