# Generated by Django 6.0.3 on 2026-03-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hik_gateway', '0008_alter_attendancecorrection_arrival_time_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancecorrection',
            new_name='hik_gateway_tenant__c2a2f7_idx',
            old_name='hik_gateway_tenant__ec96da_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancecorrection',
            new_name='hik_gateway_tenant__980e48_idx',
            old_name='hik_gateway_tenant__68ba79_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancecorrectionlog',
            new_name='hik_gateway_tenant__2b2f61_idx',
            old_name='hik_gateway_tenant__a88c5e_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancecorrectionlog',
            new_name='hik_gateway_tenant__84ebb8_idx',
            old_name='hik_gateway_tenant__f57101_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancelog',
            new_name='hik_gateway_normali_9a5efd_idx',
            old_name='hik_gateway_normali_b31273_idx',
        ),
    ]
