# Generated by Django 5.2.16 on 2026-07-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hik_gateway",
            "0009_rename_hik_gateway_tenant__ec96da_idx_hik_gateway_tenant__c2a2f7_idx_and_more",
        ),
        ("tenants", "0010_alter_tenantmembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="kind",
            field=models.CharField(
                choices=[
                    ("hikvision", "Hikvision"),
                    ("mobile_virtual", "Mobile virtual"),
                ],
                default="hikvision",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="kind",
            field=models.CharField(
                choices=[
                    ("hikvision", "Hikvision"),
                    ("mobile_virtual", "Mobile virtual"),
                ],
                default="hikvision",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="attendancelog",
            name="source",
            field=models.CharField(
                choices=[
                    ("realtime", "Realtime"),
                    ("catchup", "Catchup"),
                    ("mobile", "Mobile"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="rawevent",
            index=models.Index(
                fields=["dedupe_key"], name="hik_gateway_dedupe__2df481_idx"
            ),
        ),
    ]
