import os
from datetime import timedelta
from django.db.backends.signals import connection_created
from django.utils.translation import gettext_lazy as _
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent

# Load .env from both project root and app dir for local/dev runs.
# Docker/container env vars still override these values at runtime.
for env_path in (PROJECT_ROOT / ".env", BASE_DIR / ".env"):
    if env_path.exists():
        load_dotenv(env_path)


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 0.1: Read SECRET_KEY from environment
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "")
if not SECRET_KEY and not _env_bool("DJANGO_DEBUG", True):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set in production (DJANGO_DEBUG=0)")
if not SECRET_KEY:
    SECRET_KEY = "dev-only-fallback-key-change-me-in-prod"

# SECURITY WARNING: don't run with debug turned on in production!
# 0.1: Read DEBUG from environment
DEBUG = _env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if host.strip()
]

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000",
    ).split(",")
    if origin.strip()
]

# Custom headers the SPA sends on tenant-scoped requests.
# Without this, the browser preflight rejects any request carrying
# `X-Tenant-Code`, which is required by every endpoint that calls
# `get_request_tenant` / `assert_can_manage_billing`.
from corsheaders.defaults import default_headers  # noqa: E402
CORS_ALLOW_HEADERS = list(default_headers) + ["x-tenant-code"]


# Application definition

INSTALLED_APPS = [
    'axes',
    'audit',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'tenants',
    'devices',
    'events',
    'employees',
    'hik_gateway',
    'billing',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': int(os.getenv("SQLITE_TIMEOUT_SECONDS", "20")),
        },
    }
}

# 0.2: Postgres support via dj_database_url
import dj_database_url as _dj_db_url
_db_url = os.getenv("DATABASE_URL")
if _db_url:
    DATABASES["default"] = _dj_db_url.parse(_db_url, conn_max_age=600)


def _configure_sqlite_pragmas(sender, connection, **kwargs):
    if connection.vendor != "sqlite":
        return
    journal_mode = os.getenv("SQLITE_JOURNAL_MODE", "WAL").strip().upper() or "WAL"
    synchronous = os.getenv("SQLITE_SYNCHRONOUS", "NORMAL").strip().upper() or "NORMAL"
    with connection.cursor() as cursor:
        cursor.execute(f"PRAGMA journal_mode={journal_mode};")
        cursor.execute(f"PRAGMA synchronous={synchronous};")


connection_created.connect(_configure_sqlite_pragmas)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "fr").strip().lower() or "fr"

LANGUAGES = [
    ('fr', _('French')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

LANGUAGE_COOKIE_NAME = os.getenv("LANGUAGE_COOKIE_NAME", "securepoint_language")
LANGUAGE_COOKIE_AGE = int(os.getenv("LANGUAGE_COOKIE_AGE", str(60 * 60 * 24 * 365)))
LANGUAGE_COOKIE_SAMESITE = "Lax"

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- DRF / JWT ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # 0.4: Rate limiting
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    }
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv("JWT_ACCESS_TOKEN_MINUTES", "15"))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv("JWT_REFRESH_TOKEN_DAYS", "7"))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'TOKEN_REFRESH_SERIALIZER': 'tenants.jwt_serializers.SafeTokenRefreshSerializer',
}

# 0.4: Axes configuration for brute force protection
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 10
AXES_COOLOFF_TIME = 1  # hour
AXES_RESET_ON_SUCCESS = True
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# 0.6: Encryption configuration for device credentials
KMS_KEY = os.getenv("KMS_KEY", "")

# 0.8: Security headers (enabled outside DEBUG)
if not DEBUG:
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# 0.8: Static files with whitenoise
STATIC_ROOT = BASE_DIR / "staticfiles"
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


SPECTACULAR_SETTINGS = {
    'TITLE': 'Hikvision Django Integration API',
    'DESCRIPTION': 'Interface web pour explorer et tester les endpoints API.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


HIK_DEVICE_GATEWAY_BASE_URL = os.getenv("HIK_DEVICE_GATEWAY_BASE_URL", "")
HIK_DEVICE_GATEWAY_USERNAME = os.getenv("HIK_DEVICE_GATEWAY_USERNAME", "")
HIK_DEVICE_GATEWAY_PASSWORD = os.getenv("HIK_DEVICE_GATEWAY_PASSWORD", "")

HIK_GATEWAY_WEBHOOK_TOKEN = os.getenv("HIK_GATEWAY_WEBHOOK_TOKEN", "")
HIK_GATEWAY_ALLOWED_IPS = [ip.strip() for ip in os.getenv("HIK_GATEWAY_ALLOWED_IPS", "").split(",") if ip.strip()]
HIK_WEBHOOK_IP = os.getenv("HIK_WEBHOOK_IP", "")
HIK_WEBHOOK_PORT = int(os.getenv("HIK_WEBHOOK_PORT", "443"))
HIK_WEBHOOK_URL = os.getenv("HIK_WEBHOOK_URL", "/api/hik/events")
try:
    HIK_EVENTS_AUTO_CATCHUP_THROTTLE_SECONDS = int(
        os.getenv("HIK_EVENTS_AUTO_CATCHUP_THROTTLE_SECONDS", "2")
    )
except ValueError:
    HIK_EVENTS_AUTO_CATCHUP_THROTTLE_SECONDS = 2
try:
    HIK_CATCHUP_LOOKBACK_HOURS = int(os.getenv("HIK_CATCHUP_LOOKBACK_HOURS", "24"))
except ValueError:
    HIK_CATCHUP_LOOKBACK_HOURS = 24
try:
    HIK_CATCHUP_FAST_ACTIVE_HOURS = int(os.getenv("HIK_CATCHUP_FAST_ACTIVE_HOURS", "48"))
except ValueError:
    HIK_CATCHUP_FAST_ACTIVE_HOURS = 48
PAYMENT_WEBHOOK_TOKEN = os.getenv("PAYMENT_WEBHOOK_TOKEN", "")

# --- Stripe billing ---
# Test mode keys come from https://dashboard.stripe.com/test/apikeys
# Switch to live keys in production by overriding the env vars at deploy time.
# Beta mode — quand activé : signup public ouvert, Stripe court-circuité,
# bandeau "Beta gratuite" exposé au frontend via /api/beta/info/.
BETA_MODE = _env_bool("BETA_MODE", False)

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
# Generated when you run `stripe listen` or by adding an endpoint in the
# Stripe dashboard. Required for production webhooks.
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
# Pin the API version so Stripe responses don't change shape unexpectedly.
STRIPE_API_VERSION = os.getenv("STRIPE_API_VERSION", "2024-06-20")
# Enable Stripe Tax (auto-VAT collection) on Checkout sessions.
# Requires Tax to be activated in your Stripe dashboard.
STRIPE_AUTOMATIC_TAX = _env_bool("STRIPE_AUTOMATIC_TAX", False)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@label-ci.com")
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", False)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", True)
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "30"))
FRONTEND_AUTH_BASE_URL = os.getenv("FRONTEND_AUTH_BASE_URL", "http://localhost:3000")

# 1.4: Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "logging.Formatter",
            "fmt": '{"time": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s"}',
        },
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json" if not DEBUG else "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "django.request": {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "hik_gateway": {"handlers": ["console"], "level": "DEBUG", "propagate": False},
    },
}

# 1.4: Sentry configuration (optional, DSN not required for tests)
SENTRY_DSN = os.getenv("SENTRY_DSN", "")
if SENTRY_DSN:
    import sentry_sdk
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        traces_sample_rate=0.1,
        environment="production" if not DEBUG else "development",
    )
