# Generated by Django 6.0.2 on 2026-02-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_dev_index_device_name_device_protocol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='dev_index',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
