# Generated by Django 6.0.2 on 2026-02-25 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_alter_device_dev_index"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="ip_address",
            field=models.GenericIPAddressField(
                default="213.156.133.202", editable=False
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="port",
            field=models.PositiveIntegerField(
                choices=[(7660, "7660"), (7661, "7661")], default=7661
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="serial_number",
            field=models.CharField(blank=True, default="", max_length=9),
        ),
        migrations.AlterField(
            model_name="device",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
            ),
        ),
    ]
