# Generated by Django 6.0.2 on 2026-03-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_device_ip_address_device_owner_device_port_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="serial_number",
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
