# Generated by Django 6.0.3 on 2026-03-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_alter_device_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_password",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="device",
            name="device_username",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
