# Generated by Django 6.0.3 on 2026-03-20 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_device_password_device_device_username'),
        ('employees', '0015_organizationinvitation_organizationmembership'),
        ('tenants', '0002_tenant_device_quota_tenant_domain_tenant_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOnboardingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('manual_review', 'Manual review')], default='pending', max_length=20)),
                ('review_reason', models.CharField(blank=True, choices=[('', 'None'), ('tenant_inactive', 'Tenant inactive'), ('domain_not_verified', 'Domain not verified'), ('quota_exceeded', 'Quota exceeded'), ('permission_denied', 'Permission denied')], default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('gateway_status', models.JSONField(blank=True, default=dict)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('sn', models.CharField(max_length=31)),
                ('dev_name', models.CharField(max_length=255)),
                ('dev_type', models.CharField(default='AccessControl', max_length=64)),
                ('device_username', models.CharField(blank=True, default='', max_length=150)),
                ('device_password', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_jobs', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_onboarding_jobs', to='employees.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_device_onboarding_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_onboarding_jobs', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='devices_dev_tenant__bccb3c_idx'), models.Index(fields=['organization', 'status'], name='devices_dev_organiz_16989f_idx'), models.Index(fields=['created_at'], name='devices_dev_created_ec7071_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceOrganizationBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_device_bindings', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_bindings', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_bindings', to='employees.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'is_primary'], name='devices_dev_organiz_51af4a_idx'), models.Index(fields=['device', 'is_primary'], name='devices_dev_device__fb235b_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'organization'), name='uq_device_org_binding')],
            },
        ),
    ]
