# Generated by Django 5.2.13 on 2026-05-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_device_id_alter_deviceonboardingjob_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_password',
        ),
        migrations.RemoveField(
            model_name='deviceonboardingjob',
            name='device_password',
        ),
        migrations.AddField(
            model_name='device',
            name='device_password_encrypted',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='deviceonboardingjob',
            name='device_password_encrypted',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
