# Generated by Django 5.2.16 on 2026-07-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0019_employee_user"),
        ("presence", "0002_site"),
        ("tenants", "0010_alter_tenantmembership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminders_enabled", models.BooleanField(default=True)),
                ("warning_enabled", models.BooleanField(default=True)),
                ("late_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punch_notification_settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeePushToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "installation_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "app_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("locale", models.CharField(blank=True, default="", max_length=8)),
                ("timezone", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_tokens",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["employee", "is_active"],
                        name="presence_em_employe_d2ac75_idx",
                    ),
                    models.Index(
                        fields=["installation_id"],
                        name="presence_em_install_74fea9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PunchReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pre_start_warning", "Pre-start warning"),
                            ("late_reminder", "Late reminder"),
                        ],
                        max_length=32,
                    ),
                ),
                ("expected_start_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("push_status", models.CharField(default="skipped", max_length=16)),
                ("email_status", models.CharField(default="skipped", max_length=16)),
                ("sms_status", models.CharField(default="skipped", max_length=16)),
                ("errors", models.JSONField(blank=True, default=dict)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punch_reminders",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "kind"], name="presence_pu_date_be5d5a_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "date", "kind"),
                        name="uq_punch_reminder_once",
                    )
                ],
            },
        ),
    ]
