# Generated by Django 6.0.3 on 2026-03-20 17:44

import django.db.models.deletion
import tenants.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='device_quota',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_domain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='not_required', max_length=16),
        ),
        migrations.AddField(
            model_name='tenant',
            name='requires_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=tenants.models.default_email_verification_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_used'], name='tenants_ema_tenant__167fc9_idx'), models.Index(fields=['expires_at'], name='tenants_ema_expires_1916bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tenant_admin', 'Tenant admin'), ('org_admin', 'Organization admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='viewer', max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'role'], name='tenants_ten_tenant__1c6fa4_idx'), models.Index(fields=['user', 'role'], name='tenants_ten_user_id_94ab23_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='uq_tenant_membership_user_tenant')],
            },
        ),
    ]
