# Generated by Django 5.2.1 on 2026-05-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_emailverificationtoken_otp_code_and_passwordresettoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationcustomrole',
            new_name='tenants_org_tenant__d957f9_idx',
            old_name='tenants_org_tenant__e7504d_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationcustomrole',
            new_name='tenants_org_organiz_d847ac_idx',
            old_name='tenants_org_organiz_4235e2_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationcustomroleassignment',
            new_name='tenants_org_tenant__950255_idx',
            old_name='tenants_org_tenant__730e83_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationcustomroleassignment',
            new_name='tenants_org_organiz_0d36ac_idx',
            old_name='tenants_org_organiz_2827f7_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='tenants_pas_user_id_1b7f3f_idx',
            old_name='tenants_pas_user_id_3ddbdd_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='tenants_pas_expires_c7cfd2_idx',
            old_name='tenants_pas_expires_2f070a_idx',
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organizationcustomrole',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organizationcustomroleassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
