# Generated by Django 5.2.13 on 2026-05-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_consentlog'),
        ('tenants', '0005_rename_tenants_org_tenant__e7504d_idx_tenants_org_tenant__d957f9_idx_and_more'),
    ]

    operations = [
    ]
