# Generated by Django 5.2.13 on 2026-05-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_merge_20260504_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsentLog',
        ),
    ]
