# Generated by Django 5.2.13 on 2026-05-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_add_consentlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consentlog',
            new_name='tenants_con_email_823887_idx',
            old_name='tenants_con_email_4dbc4c_idx',
        ),
        migrations.AlterField(
            model_name='consentlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
