# Generated by Django 5.2.16 on 2026-07-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0009_rename_tenants_con_email_4dbc4c_idx_tenants_con_email_823887_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("tenant_admin", "Tenant admin"),
                    ("org_admin", "Organization admin"),
                    ("operator", "Operator"),
                    ("viewer", "Viewer"),
                    ("employee", "Employee"),
                ],
                default="viewer",
                max_length=32,
            ),
        ),
    ]
