# Generated by Django 5.2.13 on 2026-05-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_remove_device_device_password_and_more'),
        ('events', '0002_alter_attendanceevent_id'),
        ('tenants', '0005_rename_tenants_org_tenant__e7504d_idx_tenants_org_tenant__d957f9_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['tenant', 'created_at'], name='events_atte_tenant__7d7e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['device', 'timestamp'], name='events_atte_device__c00144_idx'),
        ),
    ]
