# Generated by Django 6.0.3 on 2026-03-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employees.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='employees.organization'),
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_departments', to='employees.planning'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['tenant', 'name'], name='employees_o_tenant__e1e44b_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_organization_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='planning',
            index=models.Index(fields=['tenant', 'name'], name='employees_p_tenant__76e3c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='planning',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_planning_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'organization'], name='employees_d_tenant__e09328_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'parent'], name='employees_d_tenant__ae5e12_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_department_org_code'),
        ),
    ]
