# Generated by Django 6.0.3 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_access_group_employee_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeattribute",
            name="value",
            field=models.TextField(default=""),
        ),
    ]
