# Generated by Django 6.0.3 on 2026-03-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_gateway_push_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employee',
            new_name='employees_e_tenant__c04deb_idx',
            old_name='employees_em_tenant__44cc20_idx',
        ),
    ]
