# Generated by Django 6.0.3 on 2026-03-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_device_password_device_device_username'),
        ('employees', '0006_rename_employees_em_tenant__44cc20_idx_employees_e_tenant__c04deb_idx'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_groups', to='employees.planning')),
                ('readers', models.ManyToManyField(blank=True, related_name='access_groups', to='devices.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_groups', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='access_groups',
            field=models.ManyToManyField(blank=True, related_name='employees', to='employees.accessgroup'),
        ),
        migrations.AddIndex(
            model_name='accessgroup',
            index=models.Index(fields=['tenant', 'name'], name='employees_a_tenant__697a0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessgroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_access_group_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='accessgroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_access_group_tenant_code'),
        ),
    ]
