# Generated by Django 6.0.3 on 2026-03-12 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_accessgroup_employee_access_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningDailySlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                (
                    "slot_type",
                    models.CharField(
                        choices=[("work", "Work"), ("shift", "Shift"), ("rest", "Rest")],
                        default="work",
                        max_length=16,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("label", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "planning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_slots",
                        to="employees.planning",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="planning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_employees",
                to="employees.planning",
            ),
        ),
        migrations.AddIndex(
            model_name="planningdailyslot",
            index=models.Index(fields=["planning", "day_of_week"], name="employees_p_plannin_97ea5a_idx"),
        ),
        migrations.AddConstraint(
            model_name="planningdailyslot",
            constraint=models.UniqueConstraint(
                fields=("planning", "day_of_week", "slot_type", "start_time", "end_time"),
                name="uq_planning_daily_slot",
            ),
        ),
    ]
