# Generated by Django 6.0.3 on 2026-03-13 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_planning_and_daily_slots'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='planningdailyslot',
            new_name='employees_p_plannin_33e383_idx',
            old_name='employees_p_plannin_97ea5a_idx',
        ),
        migrations.AddField(
            model_name='workshift',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='department',
            name='work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_departments', to='employees.workshift'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='employees.workshift'),
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['tenant', 'name'], name='employees_w_tenant__e6b594_idx'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_work_shift_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_work_shift_tenant_name'),
        ),
    ]
