# Generated by Django 6.0.3 on 2026-03-13 09:18

from django.db import migrations, models


def copy_existing_work_shift_to_many_to_many(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")

    for employee in Employee.objects.exclude(work_shift_id__isnull=True).iterator():
        employee.work_shifts.add(employee.work_shift_id)


def reverse_copy_existing_work_shift_to_many_to_many(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")

    for employee in Employee.objects.all().iterator():
        first_shift = employee.work_shifts.order_by("id").first()
        if first_shift is not None:
            employee.work_shift_id = first_shift.id
            employee.save(update_fields=["work_shift"])


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_workshift_break_end_time_workshift_break_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_shifts',
            field=models.ManyToManyField(blank=True, related_name='employees', to='employees.workshift'),
        ),
        migrations.RunPython(
            copy_existing_work_shift_to_many_to_many,
            reverse_code=reverse_copy_existing_work_shift_to_many_to_many,
        ),
    ]
