# Generated by Django 6.0.3 on 2026-03-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_work_shifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='employees.planning')),
                ('work_shifts', models.ManyToManyField(blank=True, related_name='planning_periods', to='employees.workshift')),
            ],
            options={
                'indexes': [models.Index(fields=['planning', 'start_date', 'end_date'], name='employees_p_plannin_468056_idx')],
                'constraints': [models.UniqueConstraint(fields=('planning', 'label', 'start_date', 'end_date'), name='uq_planning_period_range')],
            },
        ),
    ]
