# Generated by Django 6.0.3 on 2026-03-15 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_planningperiod'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('include_sub_departments', models.BooleanField(default=False)),
                ('check_in_not_required', models.BooleanField(default=False)),
                ('check_out_not_required', models.BooleanField(default=False)),
                ('effective_for_holiday', models.BooleanField(default=True)),
                ('effective_for_overtime', models.BooleanField(default=True)),
                ('flexible_weekend', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_assignments', to='employees.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_assignments', to='employees.employee')),
                ('planning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='employees.planning')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_assignments', to='tenants.tenant')),
                ('work_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='employees.workshift')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'valid_from', 'valid_to'], name='employees_p_tenant__622f92_idx'), models.Index(fields=['tenant', 'department', 'valid_from'], name='employees_p_tenant__deebb3_idx'), models.Index(fields=['tenant', 'employee', 'valid_from'], name='employees_p_tenant__1b8b14_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('sequence_index', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='employees.planning')),
                ('work_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_entries', to='employees.workshift')),
            ],
            options={
                'indexes': [models.Index(fields=['planning', 'day_of_week'], name='employees_p_plannin_1841b8_idx'), models.Index(fields=['planning', 'sequence_index'], name='employees_p_plannin_39828b_idx'), models.Index(fields=['planning', 'start_date', 'end_date'], name='employees_p_plannin_d16e88_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('day_of_week__isnull', False), ('sequence_index__isnull', False), ('start_date__isnull', False), ('end_date__isnull', False), _connector='OR'), name='ck_planning_entry_selector')],
            },
        ),
    ]
