# Generated by Django 6.0.3 on 2026-03-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0013_planningassignment_planningentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshift",
            name="early_leave_allowable_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workshift",
            name="late_allowable_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
