# Generated by Django 6.0.3 on 2026-03-20 17:44

import django.db.models.deletion
import employees.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_workshift_late_allowable_minutes_and_more'),
        ('tenants', '0002_tenant_device_quota_tenant_domain_tenant_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('org_admin', 'Org Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='viewer', max_length=32)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(default=employees.models.default_invitation_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_organization_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_organization_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='employees.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_invitations', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='employees_o_tenant__127f55_idx'), models.Index(fields=['organization', 'status'], name='employees_o_organiz_2f6ce3_idx'), models.Index(fields=['email'], name='employees_o_email_80367f_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('org_admin', 'Org Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='viewer', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='employees.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'role'], name='employees_o_organiz_b5687f_idx'), models.Index(fields=['user', 'role'], name='employees_o_user_id_96b580_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='uq_org_membership_user_org')],
            },
        ),
    ]
