# Generated by Django 6.0.3 on 2026-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
